apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels:
    run: webapp
spec:
  containers:
    - name: httpd
      image: httpd
      ports:
        - containerPort: 80
      resources:
        limits:
          memory: '128Mi'
          cpu: '250m'
    - name: redis
      image: redis:alpine
      resources:
        limits:
          memory: '128Mi'
          cpu: '250m'
