apiVersion: v1
kind: Pod
metadata:
  name: mandalorian-gifs
  labels:
    name: mandalorian-gifs
spec:
  containers:
    - name: mandalorian-gifs
      image: mandalorian-gifs-python
      imagePullPolicy: IfNotPresent
      envFrom:
        - secretRef:
            name: mandalorian-gifs-secrets
      readinessProbe:
        httpGet:
          path: /
          port: 8080
      resources:
        limits:
          memory: "128Mi"
          cpu: "250m"
      ports:
        - containerPort: 8080