apiVersion: v1
kind: Pod
metadata:
  name: devjokes-nginx
  labels:
    name: devjokes-nginx
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      ports:
        - containerPort: 80
        - containerPort: 443
      volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d
      resources:
        limits:
          memory: "128Mi"
          cpu: "250m"
    - name: devjokes
      image: devjokes
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8000
      resources:
        limits:
          memory: "128Mi"
          cpu: "250m"
      livenessProbe:
        httpGet:
          path: /healthy
          port: 8000
  volumes:
    - name: nginx-conf
      configMap:
        name: devjokes-nginx-conf
