apiVersion: v1
kind: ConfigMap
metadata:
  name: devjokes-nginx-conf
data:
  nginx.conf: |-
    upstream app {
        server localhost:8000;
    }

    server {
        server_name localhost;

        location / {
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Host $http_host;
            proxy_set_header Authorization $http_authorization;
            proxy_pass http://app/;

            proxy_connect_timeout       300;
            proxy_read_timeout          300;
            client_max_body_size        1000m;
        }
    }
