apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  minReadySeconds: 10
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      # Rolling
      maxUnavailable: 20%
      maxSurge: 0%
      # Blue/Green
      # maxUnavailable: 0%
      # maxSurge: 100%
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.24 # nginx:1.24-alpine, nginx:1.25-alpine
        ports:
        - containerPort: 80