apiVersion: v1
kind: PersistentVolume
metadata:
  name: website-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/website
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: website-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: website
spec:
  containers:
    - name: website
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
      - mountPath: /usr/share/nginx/html
        name: website
  volumes:
    - name: website
      persistentVolumeClaim:
        claimName: website-claim